[package]
name = "yewtil-macro"
version = "0.3.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Macros to be re-exported from the yewtil crate"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.73", features = ["full", "extra-traits"] }
