branches:
  only:
    - staging
    - trying
    - master

dist: trusty
language: rust
sudo: false
addons:
  firefox: latest

cache: cargo
before_cache:
  - ./ci/clear_cache.sh

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

rust:
  - 1.42.0 # min supported
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
  fast_finish: true

install:
  - nvm install 9
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup install stable
  - rustup target add wasm32-unknown-unknown
  - cargo +stable install wasm-bindgen-cli
  - curl --retry 5 -LO https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz
  - ./ci/install_cargo_web.sh

script:
  - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        export CARGO_INCREMENTAL=0;
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort";
        export RUSTDOCFLAGS="-Cpanic=abort";
      fi
  - ./ci/run_stable_checks.sh
  - GECKODRIVER=$(pwd)/geckodriver ./ci/run_tests.sh
  - |
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
      zip -0 ccov.zip `find . \( -name "grcov*.gc*" -o -name "llvmgcov.gc*" \) -print`;
      ./target/debug/yew ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info --excl-line "#\[derive\(" --excl-br-line "#\[derive\(";
      bash <(curl -s https://codecov.io/bash) -f lcov.info;
    fi
  - |
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
      zip -0 ccov.zip `find . \( -name "grcov*.gc*" -o -name "llvmgcov.gc*" \) -print`;
      ./target/debug/yew_macro ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info --excl-line "#\[derive\(" --excl-br-line "#\[derive\(";
      bash <(curl -s https://codecov.io/bash) -f lcov.info;
    fi
