[package]
name = "crm"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
serde = "1.0.126"
serde_derive = "1.0.126"
yew = { path = "../../packages/yew" }
yew-services = { path = "../../packages/yew-services" }
