[package]
name = "yew-functional-macro"
version = "0.1.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.73", features = ["full"] }

# testing
[dev-dependencies]
rustversion = "1.0.5"
trybuild = "1.0.42"
yew = { path = "../yew" }
yew-functional = { path = "../yew-functional" }
