[package]
name = "router"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
instant = { version = "0.1.9", features = ["wasm-bindgen"] }
lipsum = "0.8.0"
log = "0.4.14"
getrandom = { version = "0.2.3", features = ["js"] }
rand = { version = "0.8.4", features = ["small_rng"] }
wasm-logger = "0.2.0"
yew = { path = "../../packages/yew" }
yew-router = { path = "../../packages/yew-router" }
yewtil = { path = "../../packages/yewtil" }
yew-services = { path = "../../packages/yew-services" }
serde = { version = "1.0.126", features = ["derive"] }
lazy_static = "1.4.0"
