[package]
name = "futures"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
pulldown-cmark = { version = "0.8.0", default-features = false }
wasm-bindgen = "0.2.74"
wasm-bindgen-futures = "0.4.24"
yew = { path = "../../packages/yew" }
yewtil = { path = "../../packages/yewtil", features = ["future"] }
yew-services = { path = "../../packages/yew-services" }

[dependencies.web-sys]
version = "0.3.51"
features = [
  "Headers",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
