name: Documentation tests
on:
  push:
    paths:
      - "./**/*.md"
      - "./ci/dictionary.txt"
  pull_request:
    paths:
      - "./**/*.md"
      - "./ci/dictionary.txt"

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check spelling
        run: bash ci/spellcheck.sh list
