name: Documentation tests
on:
  push:
    paths:
      - "docs/**/*"
  pull_request:
    paths:
      - "docs/**/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Run tests
        run: cd docs && cargo test
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check spelling
        run: bash ci/spellcheck.sh list
